### ISSUE TITLE
Can you please upload the data files which you shown in the class?

### ISSUE THREAD

**Issue by kannankandasamy** [Guvi-MentorDE/BE_batch_Guvi_Aug6#32]
If already uploaded can you please provide path?

**Comment by Guvi-MentorDE** [comment]
Yes pls check the master branch for Hadoop folder. Or you can refer to
hadoop branch

**Comment by kannankandasamy** [comment]
hadoop folder contains only basics.txt in both master and hadoop branches, i do not see data folder...
